WIP for #99488428

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -33,12 +33,20 @@ password=$(jq -r '.source.password // ""' < $payload)
 email=$(jq -r '.source.email // ""' < $payload)
 repository="$(jq -r '.source.repository // ""' < $payload)"
 tag="$(jq -r '.source.tag // "latest"' < $payload)"
+ca_cert=$(jq -r '.source.ca_cert // ""' < $payload)
+
+if [ -n "$ca_cert" ] && [ -n "$insecure_registries" ]; then
+  echo "unable to specify both insecure registries and CA certificate" >&2
+  exit 1
+fi
 
 if private_registry "${repository}" ; then
   registry="$(extract_registry "${repository}")"
 else
   registry=
 fi
+
+tls_options=$(tls_options "$ca_cert")
 
 digest="$(jq -r '.version.digest' < $payload)"
 
@@ -52,26 +60,26 @@ image_name="${repository}@${digest}"
 
 if [ "$skip_download" = "false" ]; then
   if [ -n "${username}" ] && [ -n "${password}" ] && [ -n "${email}" ]; then
-    docker login -u "${username}" -p "${password}" -e "${email}" ${registry}
+    docker "{$tls_options}" login -u "${username}" -p "${password}" -e "${email}" ${registry}
   fi
 
   docker_pull "$image_name"
 
   if [ "$save" = "true" ]; then
-    docker save -o ${destination}/image "$image_name"
+    docker "{$tls_options}" save -o ${destination}/image "$image_name"
   fi
 
-  docker run \
+  docker "{$tls_options}" run \
     --cidfile=/tmp/container.cid \
     -v /opt/resource/print-metadata:/tmp/print-metadata \
     --entrypoint /tmp/print-metadata  \
     "$image_name" > ${destination}/metadata.json
 
   mkdir -p ${destination}/rootfs/
-  docker export $(cat /tmp/container.cid) | tar -xf - -C ${destination}/rootfs/
+  docker "{$tls_options}" export $(cat /tmp/container.cid) | tar -xf - -C ${destination}/rootfs/
 
   if [ "$rootfs" = "true" ]; then
-    docker export $(cat /tmp/container.cid) > ${destination}/rootfs.tar
+    docker "{$tls_options}" export $(cat /tmp/container.cid) > ${destination}/rootfs.tar
   fi
 fi
 
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -34,7 +34,12 @@ username=$(jq -r '.source.username // ""' < $payload)
 password=$(jq -r '.source.password // ""' < $payload)
 email=$(jq -r '.source.email // ""' < $payload)
 repository=$(jq -r '.source.repository // ""' < $payload)
+ca_cert=$(jq -r '.source.ca_cert // ""' < $payload)
 
+if [ -n "$ca_cert" ] && [ -n "$insecure_registries" ]; then
+  echo "unable to specify both insecure registries and CA certificate" >&2
+  exit 1
+fi
 
 if private_registry "${repository}" ; then
   registry="$(extract_registry "${repository}")"
@@ -42,8 +47,10 @@ else
   registry=
 fi
 
+tls_options=$(tls_options "$ca_cert")
+
 if [ -n "${username}" ] && [ -n "${password}" ] && [ -n "${email}" ]; then
-  docker login -u "${username}" -p "${password}" -e "${email}" ${registry}
+  docker "{$tls_options}" login -u "${username}" -p "${password}" -e "${email}" ${registry}
 fi
 
 tag_source=$(jq -r '.source.tag // "latest"' < $payload)
@@ -87,8 +94,8 @@ pull_tag=$(jq -r '.params.pull_tag // "latest"' < $payload)
 rootfs="$(jq -r '.params.rootfs' < $payload)"
 
 if [ -n "$load_base" ]; then
-  docker load -i "${load_base}/image"
-  docker tag \
+  docker "{$tls_options}" load -i "${load_base}/image"
+  docker "{$tls_options}" tag \
     "$(cat "${load_base}/image-id")" \
     "$(cat "${load_base}/repository"):$(cat "${load_base}/tag")"
 fi
@@ -99,19 +106,19 @@ if [ -n "$build" ]; then
   fi
 
   if [ -n "$dockerfile" ]; then
-    docker build -t "${repository}:${tag_name}" -f "$dockerfile" "$build"
+    docker "{$tls_options}" build -t "${repository}:${tag_name}" -f "$dockerfile" "$build"
   else
-    docker build -t "${repository}:${tag_name}" "$build"
+    docker "{$tls_options}" build -t "${repository}:${tag_name}" "$build"
   fi
   
 elif [ -n "$load_file" ]; then
-  docker load -i "$load_file"
-  docker tag "${load_repository}:${load_tag}" "${repository}:${tag_name}"
+  docker "{$tls_options}" load -i "$load_file"
+  docker "{$tls_options}" tag "${load_repository}:${load_tag}" "${repository}:${tag_name}"
 elif [ -n "$import_file" ]; then
-  cat "$import_file" | docker import - "${repository}:${tag_name}"
+  cat "$import_file" | docker "{$tls_options}" import - "${repository}:${tag_name}"
 elif [ -n "$pull_repository" ]; then
-  docker pull "${pull_repository}:${pull_tag}"
-  docker tag "${pull_repository}:${pull_tag}" "${repository}:${tag_name}"
+  docker "{$tls_options}" pull "${pull_repository}:${pull_tag}"
+  docker "{$tls_options}" tag "${pull_repository}:${pull_tag}" "${repository}:${tag_name}"
 else
   echo "must specify build or image param"
   exit 1
@@ -120,8 +127,8 @@ fi
 image_id="$(image_from_tag "$repository" "$tag_name")"
 
 if [ "$rootfs" = "true" ]; then
-  docker run --cidfile=container.cid "$image_id" echo container created
-  docker export $(cat container.cid) > ${destination}/rootfs.tar
+  docker "{$tls_options}" run --cidfile=container.cid "$image_id" echo container created
+  docker "{$tls_options}" export $(cat container.cid) > ${destination}/rootfs.tar
 fi
 
 # afaict there's no clean way to get the digest after a push. docker prints
@@ -134,7 +141,7 @@ fi
 # careful to not let 'tee' mask exit status
 
 {
-  if ! docker push "${repository}:${tag_name}"; then
+  if ! docker "{$tls_options}" push "${repository}:${tag_name}"; then
     touch /tmp/push-failed
   fi
 } | tee push-output
@@ -146,8 +153,8 @@ fi
 digest="$(tail -1 push-output | awk '{print $3}')"
 
 if [ "$need_tag_as_latest" = "true" ] && [ "${tag_name}" != "latest"  ]    ; then
-  docker tag "${repository}:${tag_name}" "${repository}:latest"
-  docker push "${repository}:latest"
+  docker "{$tls_options}" tag "${repository}:${tag_name}" "${repository}:latest"
+  docker "{$tls_options}" push "${repository}:latest"
   echo "${repository}:${tag_name} tagged as latest"
 fi
 
